### ISSUE TITLE
LTE is not working

### ISSUE THREAD

**Issue by LeVadim** [sixfab/Sixfab_RPi_CellularIoT_App_Shield#1]
Data module is not working, please advise what are the steps do debug it / fix it.

Thank yoy

**Comment by saeedjohar** [comment]
Please share the error you are getting

**Comment by jefflancaster** [comment]
uname -a
Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.8 (stretch)
Release:	9.8
Codename:	stretch

sudo qmi-network /dev/cdc-wdm0 start
Loading profile at /etc/qmi-network.conf...
    APN: nxt17.net
    APN user: unset
    APN password: unset
    qmi-proxy: no
Checking data format with 'qmicli -d /dev/cdc-wdm0 --wda-get-data-format '...
Device link layer protocol retrieved: raw-ip
Getting expected data format with 'qmicli -d /dev/cdc-wdm0 --get-expected-data-format'...
Expected link layer protocol retrieved: 802-3
Updating kernel link layer protocol with 'qmicli -d /dev/cdc-wdm0 --set-expected-data-format=raw-ip'...
Kernel link layer protocol updated
Starting network with 'qmicli -d /dev/cdc-wdm0 --wds-start-network=apn='nxt17.net'  --client-no-release-cid '...
error: couldn't start network: QMI protocol error (64): '(null)'
Saving state at /tmp/qmi-network-state-cdc-wdm0... (CID: 17)
error: network start failed, no packet data handle
Clearing state at /tmp/qmi-network-state-cdc-wdm0...

**Comment by d4rkd0s** [comment]
I think this issue can be closed. I purchased a https://sixfab.com/product/raspberry-pi-cellular-iot-application-hat/ and downloaded the latest software and it worked for me! For my provider I'm using Ting https://ting.com/
