### ISSUE TITLE
Cellular IoT HAT UDP connectToOperator

### ISSUE THREAD

**Issue by AntoineBore** [sixfab/Sixfab_RPi_CellularIoT_App_Shield#10]
Hello,

I'm following the tutorial for the Cellular IoT HAT UDP.
When i launch the basicUDP.py script, it stops at this operation : 

`Modem configuration : GSM_MODE
Trying to connect base station of operator...
AT+CGATT?
AT+CGATT?
AT+CGATT?
AT+CGATT?
AT+CGATT?
`

I have connected my HAT to a Raspberry PI 3 model B.  My laptop is connected to the internet with WiFi. The Pi is connected to my laptop with an Ethernet cable. I have shared the connection of the Wifi with the ethernet.

I think the problem is the port forwarding. ~~The IP address of my PC is 192.168.1.XX/24 so I port forward this IP. Although, the IP address of the PI is 192.168.137.XX/24~~. I don't know if this is correct or not.

PS: for my application, i cannot directly plug the PI with the rooter. Now my laptop IP is 192.168.1.46 and the raspberry IP is 192.168.1.47

Do you have any idea to solve this problem ?

Edit : I'm now able to have an IP of my router network for the PI but it still doesn't work at the same step.

**Comment by saeedjohar** [comment]
Hi, 

Does your SIM support GSM?
