### ISSUE TITLE
AT commands gives no reply, jsut keep on repeating 

### ISSUE THREAD

**Issue by holypulse2** [sixfab/Sixfab_RPi_CellularIoT_App_Shield#2]
I have tried to use the sample codes given in sample folder. none of them is working except 'sensor_test.py'
the AT commands repeat themselves on the terminal.
can i use some AT commands without using the sim?

**Comment by selengalp** [comment]
Hello,
Yes, you can use some AT commands without sim. Your issue may reason this two things below:

1 - Did you enable RPi UART interface? If you didn't, these instructions below may lead to you the solution.

Enable serial_hw and I2C interfaces by following instructions below:
```
1 - Run sudo raspi-config
2 - Select 5 Interfacing Options
3 - Enable P5 I2C
4 - For P6 Serial
  * Disable Login shell to be accessible over serial (Attention: this is important!)
  * Enable Serial port hardware
5 - Finish
6 - Reboot RPi
It's done.
```
2 - What is your RPi version that you use. Example codes are suitable for direct use of RPi 3. UART serial port is default ttyS0 in the library. If you use an older version of RPi, your UART serial port should be ttyAMA0. In this situation, you must pass an extra parameter in init() method. For RPi 2, RPi A+, RPi B+ please change as below the initialization of the library class in the example you want to run:

`node = cellulariot.CellularIoTApp(serial_port="/dev/ttyAMA0")`

**Comment by bilalahmed13** [comment]
Thanks for your reply, i am testing it shortly and then let you know the results

**Comment by bilalahmed13** [comment]
Got it working ow. I have raspberry pi 3b. The issue was with my uart actually. It was not working and hence not giving commands to the shield. My serial port was ttyS0. Thanks for your help
