### ISSUE TITLE
Unable to send data to Thingspeak

### ISSUE THREAD

**Issue by rajanya91** [sixfab/Sixfab_RPi_CellularIoT_App_Shield#3]
When I run the ThingSpeak.py file from sample folder, I get the following error.

>  AttributeError:  'CellularIoTApp'  object has no attribute  'sendDataComm'

I have checked the cellulariot.py file and 'sendDataComm' method is not defined

Please help

**Comment by selengalp** [comment]
If you installed the library with pip, your library may be old release. Please follow instructions below and install the library from Github repo again and share with us the results.
```
git clone https://github.com/sixfab/Sixfab_RPi_CellularIoT_Library.git
cd Sixfab_RPi_CellularIoT_Library
sudo python3 setup.py install
```
Also thank you for your feedback. We will update the library at pip soon.

**Comment by rajanya91** [comment]
> If you installed the library with pip, your library may be old release. Please follow instructions below and install the library from Github repo again and share with us the results.
> 
> ```
> git clone https://github.com/sixfab/Sixfab_RPi_CellularIoT_Library.git
> cd Sixfab_RPi_CellularIoT_Library
> sudo python3 setup.py install
> ```
> Also thank you for your feedback. We will update the library at pip soon.

I am still getting the same error.

**Comment by saucompeng** [comment]
Can you try again? I added a bug fix.

**Comment by rajanya91** [comment]
It is working now. Thank you for the bug fix
