### ISSUE TITLE
ppp installer

### ISSUE THREAD

**Issue by abhatikar** [sixfab/Sixfab_RPi_CellularIoT_App_Shield#4]
Hi,

@saeedjohar I am using this shield with RPI3 and not able to configure vodafone ireland normal sim for cellular internet using the ppp installer.

Also, the results from the samples here are also inconsistent.

Am i missing something ?

thanks,
Abhijeet

**Comment by saeedjohar** [comment]
Hi Abhijeet, 
At which step are you facing error? 
Please share the error log if you got any.

**Comment by saeedjohar** [comment]
The error was _not replacing default route to wlan0_
Running the following commands will solve the issue, 
**sudo route del default**
**sudo route add default ppp0**
