### ISSUE TITLE
Unable to conect via USB and not sending SMS through UART

### ISSUE THREAD

**Issue by PankajJain5889** [sixfab/Sixfab_RPi_CellularIoT_App_Shield#5]
I am trying to connect the shield via USB but Its not responding is there any extra step for it cause I was not able to find anything. Also I tried sending SMS when connected to GPIO/UART. It is unable to send SMS.  The code flow is as follows  
sudo python3 Sixfab_RPi_CellularIoT_App_Shield/sample/sendSMS.py

Sixfab Raspberry Pi Cellular IoT Shield Class initialized!
BG96 module disabled!
BG96 module enabled!
BG96 module powered up!

RDY

ATE1
ATE1
OK

AT+CMGF=1
AT+CMGF=1
OK

AT+CMGS="**************"
AT+CMGS="**************"
>
hello world!

**Comment by PankajJain5889** [comment]
In Case of basicUDP.py it never gets past ATE1 command

**Comment by saeedjohar** [comment]
During creating the instance; 
node = cellulariot.CellularIoT()
It is created with default port as /dev/ttyS0 
 while connected with USB use /dev/ttyUSB3 for internet connection. 

Please use the updated Libray to utilize sendSMS.py and basicUDP.py scripts.

**Comment by PankajJain5889** [comment]
I tried connecting by changing the sendSMS.py as follows
'''
  sendSMS.py - This is basic SMS Service example.
  Created by Yasin Kaya (selengalp), October 31, 2018.
'''
from cellulariot import cellulariot
import time

node = cellulariot.CellularIoT(serial_port="/dev/ttyUSB3")
node.disable()
time.sleep(0.5)
node.enable()
time.sleep(0.5)
node.powerUp()

node.getResponse("RDY")
node.sendATComm("ATE1","OK\r\n")

node.sendSMS("xxxxxxxxxxxxx","hello world!")

It doesn't work the error is that no ttyUSB3 found and I tried sudo rpi-update still no help.

I kept the file same and connected it to UART pins it works for sensor_test.py which is absurd

**Comment by PankajJain5889** [comment]
tried running sendSMS.py over UART pins 
this is the result
![screenshot from 2018-11-27 12-15-03](https://user-images.githubusercontent.com/44067851/49105473-d711e080-f23d-11e8-9231-0935e0ce0212.png)


My doubt is that its not able to send the last character "CTRL+ Z" cause when I run this raspi instead of ssh it gives the debug_print of \x1A

**Comment by PankajJain5889** [comment]
My bad I was using Verizon sim card and did not had my device set up with them will work on that. When using lycamobile sim set the GSM mode to any and problem was solved

**Comment by selengalp** [comment]
solved
